arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
     - joint_a1
     - joint_a2
     - joint_a3
     - joint_a4
     - joint_a5
  constraints:
    goal_time: 0.5                   # Override default
    stopped_velocity_tolerance: 0.02 # Override default
    joint_a1:
      trajectory: 1.0               # Not enforced if unspecified
      goal: 0.5                     # Not enforced if unspecified
    joint_a2:
      trajectory: 1.0               # Not enforced if unspecified
      goal: 0.5                     # Not enforced if unspecified
    joint_a3:
      trajectory: 1.0               # Not enforced if unspecified
      goal: 0.5                     # Not enforced if unspecified
    joint_a4:
      trajectory: 1.0               # Not enforced if unspecified
      goal: 0.5                     # Not enforced if unspecified
    joint_a5:
      trajectory: 1.0               # Not enforced if unspecified
      goal: 0.5                     # Not enforced if unspecified
  gains:
    joint_a1: {p: 10000.0, i: 1.0, d: 10.0}
    joint_a2: {p: 10000.0, i: 1.0, d: 10.0}
    joint_a3: {p: 10000.0, i: 1.0, d: 10.0}
    joint_a4: {p: 10000.0, i: 1.0, d: 10.0}
    joint_a5: {p: 10000.0, i: 1.0, d: 10.0}
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
     - gripper_joint
     - sub_gripper_joint
  constraints:
    goal_time: 0.5                   # Override default
    stopped_velocity_tolerance: 0.02 # Override default
    gripper_joint:
      trajectory: 1.0               # Not enforced if unspecified
      goal: 0.5                     # Not enforced if unspecified
    sub_gripper_joint:
      trajectory: 1.0               # Not enforced if unspecified
      goal: 0.5                     # Not enforced if unspecified
  gains:
    gripper_joint: {p: 100.0, i: 1, d: 0.1}
    sub_gripper_joint: {p: 100.0,  i: 1, d: 0.1}